"""change Billtye body 

Revision ID: 0fed87c3fce1
Revises: 61e73bcedd5d
Create Date: 2026-03-06 03:03:46.282346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fed87c3fce1'
down_revision: Union[str, Sequence[str], None] = '61e73bcedd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_transactions_bill_id_fkey'), 'inventory_transactions', type_='foreignkey')
    
    # ⭐ FIX: Clear data and change column type to Integer
    op.execute('DELETE FROM inventory_transactions')
    op.alter_column('inventory_transactions', 'bill_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='bill_id::integer')

    op.drop_index(op.f('ix_bills_bill_id'), table_name='bills')
    op.drop_column('bills', 'bill_id')
    op.create_foreign_key(None, 'inventory_transactions', 'bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_model_number', 'items', ['model_number'], unique=False)
    op.create_index(op.f('ix_items_model_number'), 'items', ['model_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_model_number'), table_name='items')
    op.drop_index('idx_model_number', table_name='items')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.add_column('bills', sa.Column('bill_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_bills_bill_id'), 'bills', ['bill_id'], unique=True)
    
    # ⭐ FIX: Revert column type to String on downgrade
    op.alter_column('inventory_transactions', 'bill_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
               
    op.create_foreign_key(op.f('inventory_transactions_bill_id_fkey'), 'inventory_transactions', 'bills', ['bill_id'], ['bill_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
