"""modify Item table add column name quantity

Revision ID: 3702a3f94354
Revises: 38a31c4253df
Create Date: 2026-01-14 13:19:16.033437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3702a3f94354'
down_revision: Union[str, Sequence[str], None] = '38a31c4253df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
