"""change all table relationship and make table inventory

Revision ID: 78ff83c87ece
Revises: 81aaa0e56a4e
Create Date: 2026-01-12 13:08:45.500798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ff83c87ece'
down_revision: Union[str, Sequence[str], None] = '81aaa0e56a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
