"""change model_number as nullable False

Revision ID: 81aaa0e56a4e
Revises: cd6442112481
Create Date: 2026-01-11 23:25:07.322185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81aaa0e56a4e'
down_revision: Union[str, Sequence[str], None] = 'cd6442112481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'model_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'model_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
