"""add two columns item table as sell and buy price

Revision ID: ae042c5a0d7e
Revises: 5f1a24a9a1b5
Create Date: 2026-01-14 18:41:11.566227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae042c5a0d7e'
down_revision: Union[str, Sequence[str], None] = '5f1a24a9a1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('buying_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('items', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'selling_price')
    op.drop_column('items', 'buying_price')
    # ### end Alembic commands ###
